"""Proof that a third shell surface is a config-only addition."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from screenscribe.shell import render_surface
from screenscribe.shell.demo_surface import DEMO_SURFACE

REPO_ROOT = Path(__file__).resolve().parents[1]

DEMO_CONFIG_PATH = Path("screenscribe/shell/demo_surface.py")
DEMO_TEST_PATH = Path("tests/test_shell_third_surface_config_only.py")
CONFIG_ONLY_PROOF_PATHS = {DEMO_CONFIG_PATH, DEMO_TEST_PATH}


def _viewer_context() -> dict[str, str]:
    return {
        "document_language": "en",
        "ui_language": "en",
        "video_name": "viewer-demo.mp4",
        "video_name_escaped": "viewer-demo.mp4",
        "body_mode": "viewer",
        "body_default_lang": "en",
        "body_speech_lang": "en",
        "body_has_markers": "false",
        "findings_json": "[]",
        "segments_json": "[]",
    }


def _repo_manifest() -> set[Path]:
    git = shutil.which("git")
    assert git is not None, "git executable is required for the file-manifest proof"
    result = subprocess.run(
        [git, "ls-files", "--cached", "--others", "--exclude-standard"],
        cwd=REPO_ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return {Path(line) for line in result.stdout.splitlines() if line}


def test_demo_surface_renders_valid_shell_document_with_declared_slots() -> None:
    html = render_surface(DEMO_SURFACE, _viewer_context())

    assert html.startswith("<!DOCTYPE html>")
    assert '<html lang="en">' in html
    assert 'data-surface-id="viewer"' in html
    assert 'data-i18n-namespace="viewer"' in html
    assert 'data-mode="viewer"' in html
    assert 'data-feature-native-video="true"' in html
    assert 'data-feature-readonly="true"' in html
    assert "<title>Screenscribe Viewer - viewer-demo.mp4</title>" in html
    assert ">Screenscribe Viewer</h1>" in html

    assert DEMO_SURFACE.main_panels == ["video_panel", "transcript_panel"]
    assert '<video id="videoPlayer" controls preload="metadata" src="/video">' in html
    assert 'id="transcriptPanel"' in html
    assert 'id="subtitleSearch"' in html

    assert "Generated by screenscribe" not in html
    assert 'id="captureFrameBtn"' not in html
    assert 'id="manualFrameModal"' not in html
    assert 'id="frameModal"' not in html
    assert "{slot:" not in html


def test_demo_surface_file_manifest_is_config_only() -> None:
    manifest = _repo_manifest()
    proof_paths = {
        path
        for path in manifest
        if path.name in {"demo_surface.py", "test_shell_third_surface_config_only.py"}
        or "viewer" in path.name.lower()
    }

    assert proof_paths == CONFIG_ONLY_PROOF_PATHS
    assert DEMO_CONFIG_PATH in manifest
    assert Path("screenscribe/shell/renderer.py") in manifest
    assert Path("screenscribe/html_pro_assets/templates/shell.html") in manifest

    forbidden_surface_runtime = {
        path
        for path in proof_paths
        if path.parts[:3] == ("screenscribe", "html_pro_assets", "templates")
        or path.parts[:3] == ("screenscribe", "html_pro_assets", "js")
        or path == Path("screenscribe/shell/renderer.py")
    }
    assert forbidden_surface_runtime == set()
