"""Static-demo mode contract (PR #1 review).

The GitHub Pages sample (``site/demo/report.html``, generated by
``examples/generate_example.py``) must be fully self-contained: no backing
server, no source recording. ``render_html_report_pro(static_demo=True)`` bakes
that mode so the client skips the ``/api/review-state`` hydration fetch and the
video panel shows an honest empty state instead of a dead player.

These are server-render assertions; the zero-network / zero-console runtime
behaviour is exercised in the headless e2e layer.
"""

from __future__ import annotations

import re

from screenscribe.html_pro.renderer import render_html_report_pro
from screenscribe.transcribe import Segment


def _body_tag(html: str) -> str:
    """The opening <body ...> tag only (the CSS also mentions the flag, so a raw
    substring check over the whole document would be ambiguous)."""
    match = re.search(r"<body\b[^>]*>", html)
    assert match, "no <body> tag rendered"
    return match.group(0)


_FINDINGS = [
    {
        "id": 1,
        "category": "bug",
        "timestamp": 3.5,
        "timestamp_formatted": "00:03",
        "text": "A finding",
        "screenshot": "",
        "unified_analysis": {"is_issue": True, "severity": "high", "summary": "s"},
    }
]
_SEGMENTS = [Segment(id=1, start=0.0, end=4.0, text="hello")]


def _render(*, static_demo: bool) -> str:
    return render_html_report_pro(
        video_name="demo.mov",
        video_path=None,
        generated_at="2026-01-01T00:00:00",
        executive_summary="",
        findings=_FINDINGS,
        segments=_SEGMENTS,
        errors=[],
        language="en",
        static_demo=static_demo,
    )


def test_default_render_keeps_the_player_and_no_static_flag() -> None:
    html = _render(static_demo=False)
    assert "data-static-demo" not in _body_tag(html)
    assert 'id="videoControls"' in html  # precision player controls present
    assert 'class="video-empty-state"' not in html


def test_static_demo_bakes_flag_empty_state_and_drops_controls() -> None:
    html = _render(static_demo=True)

    # Body flag the client reads to skip hydration / no-op seeks.
    assert 'data-static-demo="true"' in _body_tag(html)

    # The video element stays (hidden via CSS) but the interactive player
    # controls are dropped entirely — nothing to drive without a recording.
    assert 'id="videoControls"' not in html
    assert 'id="playPauseBtn"' not in html

    # Honest, re-translatable empty state in the video's place.
    assert 'class="video-empty-state"' in html
    assert 'data-i18n="staticDemoNoVideo"' in html
    assert "Sample report — the source recording is not included." in html


def test_static_demo_flag_reaches_the_embedded_client_guard() -> None:
    # The baked review_app.js carries the isStaticDemo() guard the runtime uses
    # to skip the /api/review-state fetch and no-op finding-card seeks.
    html = _render(static_demo=True)
    assert "function isStaticDemo()" in html
    assert "data-static-demo" in html  # CSS hide rule + body attr both present


def test_static_demo_message_is_single_sourced_en_pl() -> None:
    # The empty-state string lives in BOTH server-side (_SERVER_I18N) and client
    # (i18n.js I18N_BUNDLE) media namespaces with en/pl parity, so the language
    # toggle re-translates it. Guard against a half-added key.
    from pathlib import Path

    from screenscribe.shell.renderer import _SERVER_I18N

    for lang in ("en", "pl"):
        assert "staticDemoNoVideo" in _SERVER_I18N[lang]["media"]

    i18n_js = (
        Path(__file__).resolve().parent.parent / "screenscribe/html_pro_assets/scripts/i18n.js"
    ).read_text(encoding="utf-8")
    # Present under both language blocks of the JS bundle.
    assert i18n_js.count('"staticDemoNoVideo"') == 2
