"""DOM-contract tests for the shell-composed ANALYZE dashboard."""

from __future__ import annotations

import re

from screenscribe.shell import ANALYZE_SURFACE, render_surface


def _render_analyze() -> str:
    return render_surface(
        ANALYZE_SURFACE,
        {
            "document_language": "pl",
            "ui_language": "pl",
            "video_name": "kontrakt-demo.mp4",
            "video_name_escaped": "kontrakt-demo.mp4",
            "speech_lang_label": "PL",
            "body_mode": "analyze",
            "body_default_lang": "pl",
            "body_speech_lang": "pl",
            "body_has_markers": "false",
            "findings_json": "[]",
            "segments_json": "[]",
        },
    )


def _assert_ordered(html: str, needles: list[str]) -> None:
    positions = [html.index(needle) for needle in needles]
    assert positions == sorted(positions), list(zip(needles, positions, strict=True))


def test_analyze_shell_dom_contract() -> None:
    html = _render_analyze()

    assert 'data-surface-id="analyze"' in html
    assert 'data-i18n-namespace="analyze"' in html
    assert 'data-mode="analyze"' in html
    assert 'data-default-lang="pl"' in html
    assert 'data-speech-lang="pl"' in html
    assert 'data-has-markers="false"' in html
    assert 'class="workspace-shell"' in html
    assert 'class="modal-layer"' in html
    assert ">analyze</h1>" in html
    assert "Generated by screenscribe" not in html

    for critical_id in (
        "videoPlayer",
        "markerTimeline",
        "markerTimelineTrack",
        "videoStatusLine",
        "transcriptPanel",
        "subtitleSearch",
        "subtitleList",
        "sidebarResizer",
        "tab-capture",
        "tab-findings",
        "tab-export",
        "micBtn",
        "micLabel",
        "recordingStatus",
        "transcriptPreview",
        "notesInput",
        "markFrameBtn",
        "howtoSteps",
        "markersList",
        "statusText",
        "finalizeProgress",
        "finalizeProgressLabel",
        "finalizeProgressErrors",
        "finalizeProgressFill",
        "exportJsonBtn",
        "finalizeBtn",
        "exportGateHint",
        "frameModal",
        "frameModalImg",
        "langToggle",
        "speechLanguageValue",
    ):
        assert f'id="{critical_id}"' in html

    assert re.search(r'<video[^>]+id="videoPlayer"[^>]+controls[^>]+src="/video"', html)
    assert 'id="videoControls"' not in html
    assert 'class="video-controls-pro"' not in html
    assert 'id="detachReviewBtn"' not in html
    assert 'id="attachWorkspaceBtn"' not in html

    anchors = set(re.findall(r'data-i18n="([^"]+)"', html))
    assert {
        "tab_capture",
        "tab_findings",
        "tab_export",
        "meta_mode",
        "speech_language_label",
        "ui_language_label",
        "video_status_idle",
        "transcript_heading",
        "panel_heading",
        "ux_hint",
        "mic_label",
        "recording",
        "mark_frame",
        "howto_step_1",
        "howto_step_2",
        "howto_step_3",
        "howto_step_4",
        "findings_empty_1",
        "findings_empty_2",
        "status_ready",
        "export_json",
        "report_md",
        "export_gate_hint",
    }.issubset(anchors)

    attr_anchors = set(re.findall(r'data-i18n-attr="([^"]+)"', html))
    assert {
        "aria-label:marker_timeline_aria",
        "placeholder:transcript_search",
        "title:mic_title",
        "aria-label:howto_heading",
        "aria-label:markers_list_aria",
        "aria-label:modal_aria",
        "aria-label:modal_close",
        "alt:modal_alt",
    }.issubset(attr_anchors)

    for action_contract in (
        # Post-C7.2: export buttons keep stable ids and are wired in JS via
        # addEventListener (no inline onclick). frame_modal stays out of scope.
        'id="exportJsonBtn"',
        'id="finalizeBtn"',
        'onclick="event.stopPropagation(); closeFrameModal()"',
        'data-i18n-tpl="errors_count"',
        'data-i18n-tpl-args="0"',
        "X-ScreenScribe-Token",
        "?st=",
        "frame_url arrives pre-signed",
    ):
        assert action_contract in html

    _assert_ordered(
        html,
        [
            'id="original-findings"',
            "window.TRANSCRIPT_SEGMENTS",
            "window.I18N_BUNDLE",
            "attachLanguageControl",
            "attachSttTransport",
            "attachTabKeyboard",
            "class VoiceRecorder",
        ],
    )
